import { addDays, dateKey, lectureNumbersFromTitle, PLAN_START_DATE, roundToOne } from "./schedule";
import type { Course, PlannerCapacityWarning, PlannerValidationIssue, StudyMethod, StudyState, StudyTask, TaskType } from "./types";

const priorityWeight = {
  high: 0,
  medium: 1,
  low: 2,
};

const EXAM_PREP_WINDOW_DAYS = 7;
const PRESSURE_SAFE = 0.65;
const PRESSURE_WATCH = 0.85;
const PRESSURE_URGENT = 1;
const MIN_SPLIT_BLOCK_HOURS = 0.5;

type PlanOptions = {
  today: string;
  maxDailyHours: number;
  now?: Date;
  ignoreTodayClock?: boolean;
  endDate?: string;
  holidays?: string[];
  customStudyHours?: Array<{ date: string; hours: number }>;
  restrictedDays?: Array<{ date: string; maxHours: number }>;
};

type CapacityRules = {
  today: string;
  todayCapacity: number;
  holidays: Set<string>;
  customStudyHours: Map<string, number>;
};

type WorkBlock = {
  course: Course;
  method?: StudyMethod;
  title: string;
  type: TaskType;
  stage: "study" | "revision";
  hours: number;
  deadline?: string;
  customDeadline?: string;
  hardDeadline?: string;
  earliestDate: string;
  sequence: number;
  methodItem?: number;
  methodOrder: number;
  itemNumber: number;
  parentTaskId?: string;
  segmentNumber?: number;
  segmentCount?: number;
};

type CourseWorkQueue = {
  course: Course;
  blocks: WorkBlock[];
  originalIndex: number;
};

type DependencyGraphIssue = {
  type: "missing" | "cycle";
  courseId: string;
  message: string;
  path?: string[];
  courseIds?: string[];
};

export function createCourseId(name: string) {
  return name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

export function autoPlanSchedule(state: StudyState, options: PlanOptions): StudyState {
  const today = maxDate(options.today, state.settings?.startDate ?? PLAN_START_DATE);
  const settings = {
    ...state.settings,
    autoPlan: state.settings?.autoPlan ?? true,
    autoPlanIntervalHours: state.settings?.autoPlanIntervalHours ?? 24,
    maxDailyHours: options.maxDailyHours,
    startDate: state.settings?.startDate ?? PLAN_START_DATE,
    planEndDate: options.endDate ?? state.settings?.planEndDate,
    holidays: options.holidays ?? state.settings?.holidays ?? [],
    customStudyHours: options.customStudyHours ?? state.settings?.customStudyHours ?? migrateRestrictedDays(options.restrictedDays ?? state.settings?.restrictedDays),
    restrictedDays: options.restrictedDays ?? state.settings?.restrictedDays ?? [],
    lastAutoPlanDate: today,
    lastAutoPlanAt: new Date().toISOString(),
    defaultTaskHours: state.settings?.defaultTaskHours ?? 1,
    warningThresholdHours: state.settings?.warningThresholdHours ?? 8,
    showCompletedTasks: state.settings?.showCompletedTasks ?? true,
    weekStartsOn: state.settings?.weekStartsOn ?? "monday",
    reminderTime: state.settings?.reminderTime ?? "00:00",
    lateNightPromptEnabled: state.settings?.lateNightPromptEnabled ?? true,
    lateNightPromptAfterHour: state.settings?.lateNightPromptAfterHour ?? 23,
    lateNightMaxExtensionHour: state.settings?.lateNightMaxExtensionHour ?? 6,
    studyDayOverride: state.settings?.studyDayOverride,
    language: state.settings?.language ?? "en",
    theme: state.settings?.theme ?? "razor",
  };
  const todayCapacity = options.maxDailyHours;
  const capacityRules: CapacityRules = {
    today,
    todayCapacity,
    holidays: new Set(settings.holidays),
    customStudyHours: new Map(settings.customStudyHours.map((day) => [day.date, day.hours])),
  };

  const preservedTasks = state.tasks.filter((task) => shouldPreserveTaskForPlanning(task, today));
  const generatedTasks: StudyTask[] = [];
  const dailyHours = new Map<string, number>();

  for (const task of preservedTasks) {
    dailyHours.set(task.date, roundToOne((dailyHours.get(task.date) ?? 0) + task.estimatedHours));
  }

  const completedGeneratedTitles = new Set(
    preservedTasks
      .filter((task) => task.autoGenerated || task.origin === "generated")
      .map((task) => blockKey(task.courseId, task.type, task.title)),
  );
  const completedLectureNumbers = getCompletedLectureNumbers(state);
  const completedStudyItems = getCompletedStudyItems(state);
  const taskDeadlines = getTaskDeadlineOverrides(state.tasks);
  const taskOrders = getTaskOrderOverrides(state.tasks);
  const graphIssues = dependencyGraphIssues(state.courses);
  const blockedCourseIds = new Set(graphIssues.flatMap((issue) => issue.courseIds ?? [issue.courseId]));
  schedulePriorityAwareBlocks({
    courses: state.courses,
    blockedCourseIds,
    completedLectureNumbers,
    completedStudyItems,
    completedGeneratedTitles,
    taskDeadlines,
    taskOrders,
    generatedTasks,
    dailyHours,
    settings,
    today,
    todayCapacity,
    capacityRules,
  });

  const examTasks = state.courses
    .filter((course) => course.hasExam && course.examDate)
    .filter((course) => !preservedTasks.some((task) => task.type === "exam" && task.courseId === course.id))
    .map((course) => ({
      id: `exam-${course.id}-${course.examDate}`,
      date: course.examDate as string,
      title: `${course.name} exam`,
      subject: course.name,
      courseId: course.id,
      type: "exam" as const,
      phase: "Deadline",
      estimatedHours: 0,
      completed: false,
    }));

  return {
    ...state,
    settings,
    tasks: [...preservedTasks, ...generatedTasks, ...examTasks].sort((a, b) => a.date.localeCompare(b.date)),
  };
}

export function plannerCapacityWarning(state: StudyState, options: PlanOptions): PlannerCapacityWarning | undefined {
  const currentPlan = autoPlanSchedule(state, { ...options, ignoreTodayClock: true });
  const issues = validatePlannedState(currentPlan, options.today);
  const blockingIssues = issues.filter((issue) => issue.severity === "error");
  const rangeMiss = planRangeMiss(currentPlan);
  const recovery = recoverySuggestion(state, options);
  if (blockingIssues.length === 0 && !rangeMiss) {
    if (!recovery) return undefined;
    return {
      currentDailyLimit: options.maxDailyHours,
      latestScheduledDate: options.today,
      severity: "today",
      issues: [recovery.issue, ...issues],
      message: recovery.message,
    };
  }

  const suggestedDailyLimit = findMinimumDailyLimit(state, {
    today: options.today,
    endDate: options.endDate,
    holidays: options.holidays,
    customStudyHours: options.customStudyHours,
    restrictedDays: options.restrictedDays,
    minDailyHours: 1,
    maxDailyHours: 24,
  });

  if (suggestedDailyLimit !== undefined && suggestedDailyLimit <= options.maxDailyHours) {
    return undefined;
  }

  const firstIssue = blockingIssues[0];
  const latestIssueDate = blockingIssues
    .map((issue) => issue.date)
    .filter((date): date is string => Boolean(date))
    .sort()
    .at(-1);

  return {
    currentDailyLimit: options.maxDailyHours,
    suggestedDailyLimit,
    latestScheduledDate: latestIssueDate ?? rangeMiss?.latestScheduledDate ?? options.today,
    severity: firstIssue?.type === "capacity" ? "today" : "deadline",
    issues: recovery ? [recovery.issue, ...issues] : issues,
    message: rangeMiss
      ? `This plan needs work after ${rangeMiss.rangeEnd}. Easiest fix: extend the range to ${rangeMiss.latestScheduledDate} or raise the daily cap.`
      : recovery
        ? recovery.message
      : suggestedDailyLimit && firstIssue
        ? `${firstIssue.message} Raise the daily cap to ${suggestedDailyLimit}h to keep the plan feasible.`
        : "The current workload cannot fit before every deadline, even with a 24h daily cap.",
  };
}

export function debugSchedulerTrace(state: StudyState, options: PlanOptions) {
  const today = maxDate(options.today, state.settings?.startDate ?? PLAN_START_DATE);
  const preservedTasks = state.tasks.filter((task) => shouldPreserveTaskForPlanning(task, today));
  const overdueReturnedToPool = state.tasks.filter((task) =>
    !task.completed &&
    task.date < today &&
    (task.autoGenerated || task.origin === "generated") &&
    !shouldPreserveTaskForPlanning(task, today)
  );
  const planned = autoPlanSchedule(state, options);
  const issues = validatePlannedState(planned, today);
  const warning = plannerCapacityWarning(state, options);
  const generated = planned.tasks.filter((task) => task.autoGenerated);

  return {
    input: {
      today,
      maxDailyHours: options.maxDailyHours,
      courses: state.courses.length,
      tasks: state.tasks.length,
    },
    normalizedCourses: state.courses.map((course) => ({
      id: course.id,
      name: course.name,
      priority: course.priority,
      planningOrder: course.planningOrder,
      targetFinishDate: course.targetFinishDate,
      examDate: course.examDate,
      dependencies: getDependencyIds(course),
      methods: getStudyMethods(course).map((method) => ({
        id: method.id,
        totalItems: method.totalItems,
        completedItems: method.completedItems,
        hoursPerItem: method.hoursPerItem,
        taskType: method.taskType,
        orderMode: taskOrderMode(method.taskType),
        splittable: isSplittableTask(method.taskType),
      })),
    })),
    dependencyIssues: dependencyGraphIssues(state.courses),
    preservedTasks: preservedTasks.map((task) => traceTask(task)),
    overdueReturnedToPool: overdueReturnedToPool.map((task) => traceTask(task)),
    generatedTasks: generated.map((task) => traceTask(task)),
    dailyHours: [...groupHoursByDate(planned.tasks).entries()].map(([date, hours]) => ({ date, hours })),
    issues,
    warning,
  };
}

export function hoursUntilNextRollover(now = new Date(), rolloverHour = 0) {
  const nextRollover = new Date(now);
  nextRollover.setHours(rolloverHour, 0, 0, 0);
  if (nextRollover <= now) nextRollover.setDate(nextRollover.getDate() + 1);
  return Math.max(roundToOne((nextRollover.getTime() - now.getTime()) / (1000 * 60 * 60)), 0);
}

export function getTodayPlanningCapacity(maxDailyHours: number, now = new Date()) {
  hoursUntilNextRollover(now);
  return roundToOne(maxDailyHours);
}

function schedulePriorityAwareBlocks({
  courses,
  blockedCourseIds,
  completedLectureNumbers,
  completedStudyItems,
  completedGeneratedTitles,
  taskDeadlines,
  taskOrders,
  generatedTasks,
  dailyHours,
  settings,
  today,
  todayCapacity,
  capacityRules,
}: {
  courses: Course[];
  blockedCourseIds: Set<string>;
  completedLectureNumbers: Map<string, Set<number>>;
  completedStudyItems: Map<string, Map<string, Set<number>>>;
  completedGeneratedTitles: Set<string>;
  taskDeadlines: Map<string, string>;
  taskOrders: Map<string, number>;
  generatedTasks: StudyTask[];
  dailyHours: Map<string, number>;
  settings: StudyState["settings"] & { maxDailyHours: number; planEndDate?: string };
  today: string;
  todayCapacity: number;
  capacityRules: CapacityRules;
}) {
  const studyHoursByCourse = new Map(
    courses.map((course) => [
      course.id,
      studyHoursForCourse(
        course,
        completedLectureNumbers.get(course.id) ?? new Set(),
        completedStudyItems.get(course.id) ?? new Map(),
      ),
    ]),
  );
  const effectiveStudyDeadlines = resolveEffectiveStudyDeadlines(
    courses,
    studyHoursByCourse,
    settings,
    today,
    todayCapacity,
    capacityRules,
  );
  const queues = new Map<string, CourseWorkQueue>();
  courses.forEach((course, index) => {
    if (blockedCourseIds.has(course.id)) {
      queues.set(course.id, { course, blocks: [], originalIndex: index });
      return;
    }
    const studyBlocks = createStudyBlocks(
      course,
      today,
      completedLectureNumbers.get(course.id) ?? new Set(),
      completedStudyItems.get(course.id) ?? new Map(),
      effectiveStudyDeadlines.get(course.id),
      taskDeadlines,
      taskOrders,
    );
    const revisionBlocks = course.requiresRevision
      ? createRevisionBlocks(course, today)
      : [];
    const blocks = [...studyBlocks, ...revisionBlocks]
      .filter((block) => !completedGeneratedTitles.has(blockKey(course.id, block.type, block.title)))
      .sort((a, b) => (a.stage === b.stage ? 0 : a.stage === "study" ? -1 : 1) || a.sequence - b.sequence);
    queues.set(course.id, { course, blocks, originalIndex: index });
  });

  const maxDeadline = latestRealDeadline(courses);
  const horizon = addDays(maxDate(settings.planEndDate ?? today, maxDeadline ?? addDays(today, 365)), 180);
  const scheduledTodayByCourse = new Map<string, Map<string, number>>();
  const dependencyCompletionDates = new Map<string, string>();
  let cursor = today;
  let guard = 0;

  while (hasRemainingWork(queues) && cursor <= horizon && guard < 1200) {
    guard += 1;
    const capacity = capacityForDate(cursor, settings.maxDailyHours, today, todayCapacity, capacityRules);
    const used = dailyHours.get(cursor) ?? 0;
    let remainingCapacity = roundToOne(capacity - used);

    while (hasRemainingWork(queues)) {
      const candidate = chooseNextBlock({
        queues,
        date: cursor,
        remainingCapacity,
        settings,
        today,
        todayCapacity,
        capacityRules,
        scheduledToday: scheduledTodayByCourse.get(cursor) ?? new Map(),
        dependencyCompletionDates,
      });
      if (!candidate) break;

      const { queue, block } = candidate;
      const scheduledTask = makeTaskFromBlock(block, cursor);
      generatedTasks.push(scheduledTask);
      queue.blocks.shift();
      if (block.stage === "study" && !queue.blocks.some((item) => item.stage === "study")) {
        dependencyCompletionDates.set(queue.course.id, cursor);
      }
      dailyHours.set(cursor, roundToOne((dailyHours.get(cursor) ?? 0) + block.hours));
      const courseDayCounts = scheduledTodayByCourse.get(cursor) ?? new Map<string, number>();
      courseDayCounts.set(queue.course.id, (courseDayCounts.get(queue.course.id) ?? 0) + 1);
      scheduledTodayByCourse.set(cursor, courseDayCounts);
      remainingCapacity = roundToOne(remainingCapacity - block.hours);
      if (remainingCapacity <= 0) break;
    }

    cursor = addDays(cursor, 1);
  }

  if (hasRemainingWork(queues)) {
    for (const queue of queues.values()) {
      while (queue.blocks.length) {
        const block = queue.blocks.shift() as WorkBlock;
        generatedTasks.push(makeTaskFromBlock(block, cursor));
        dailyHours.set(cursor, roundToOne((dailyHours.get(cursor) ?? 0) + block.hours));
        cursor = addDays(cursor, 1);
      }
    }
  }
}

function chooseNextBlock({
  queues,
  date,
  remainingCapacity,
  settings,
  today,
  todayCapacity,
  capacityRules,
  scheduledToday,
  dependencyCompletionDates,
}: {
  queues: Map<string, CourseWorkQueue>;
  date: string;
  remainingCapacity: number;
  settings: StudyState["settings"] & { maxDailyHours: number };
  today: string;
  todayCapacity: number;
  capacityRules: CapacityRules;
  scheduledToday: Map<string, number>;
  dependencyCompletionDates: Map<string, string>;
}) {
  const candidates = [...queues.values()]
    .filter((queue) => queue.blocks.length > 0)
    .filter((queue) => dependenciesSatisfied(queue.course, queues, date, dependencyCompletionDates))
    .filter((queue) => {
      const block = queue.blocks[0];
      return block.hours <= remainingCapacity && block.earliestDate <= date;
    })
    .map((queue) => ({
      queue,
      block: queue.blocks[0],
      score: scoreQueue(queue, queues, date, settings, today, todayCapacity, capacityRules, scheduledToday),
    }))
    .sort((a, b) => compareCandidateRank(a, b, queues, date, settings, today, todayCapacity, capacityRules));

  return candidates[0];
}

function compareCandidateRank(
  a: { queue: CourseWorkQueue; block: WorkBlock; score: number },
  b: { queue: CourseWorkQueue; block: WorkBlock; score: number },
  queues: Map<string, CourseWorkQueue>,
  date: string,
  settings: StudyState["settings"] & { maxDailyHours: number },
  today: string,
  todayCapacity: number,
  capacityRules: CapacityRules,
) {
  const scoreCompare = b.score - a.score;
  if (Math.abs(scoreCompare) > 0.0001) return scoreCompare;

  const aPressure = blockPressure(a.queue, a.block, date, settings, today, todayCapacity, capacityRules);
  const bPressure = blockPressure(b.queue, b.block, date, settings, today, todayCapacity, capacityRules);
  if (bPressure.hard !== aPressure.hard) return bPressure.hard - aPressure.hard;
  if (bPressure.dependencyUnlock !== aPressure.dependencyUnlock) return bPressure.dependencyUnlock - aPressure.dependencyUnlock;

  const deadlineCompare = (realBlockDeadline(a.block) ?? "9999-12-31").localeCompare(realBlockDeadline(b.block) ?? "9999-12-31");
  if (deadlineCompare !== 0) return deadlineCompare;

  const priorityCompare = priorityWeight[a.queue.course.priority] - priorityWeight[b.queue.course.priority];
  if (priorityCompare !== 0) return priorityCompare;

  const orderCompare = planningOrder(a.queue.course, new Map([[a.queue.course.id, a.queue.originalIndex + 1], [b.queue.course.id, b.queue.originalIndex + 1]])) -
    planningOrder(b.queue.course, new Map([[a.queue.course.id, a.queue.originalIndex + 1], [b.queue.course.id, b.queue.originalIndex + 1]]));
  if (orderCompare !== 0) return orderCompare;

  if (a.block.methodOrder !== b.block.methodOrder) return a.block.methodOrder - b.block.methodOrder;
  if (a.block.itemNumber !== b.block.itemNumber) return a.block.itemNumber - b.block.itemNumber;

  return makeTaskStableId(a.block).localeCompare(makeTaskStableId(b.block));
}

function blockPressure(
  queue: CourseWorkQueue,
  block: WorkBlock,
  date: string,
  settings: StudyState["settings"] & { maxDailyHours: number },
  today: string,
  todayCapacity: number,
  capacityRules: CapacityRules,
) {
  const deadline = realBlockDeadline(block);
  if (!deadline) return { hard: 0, dependencyUnlock: dependencyUnlockPressure(queue.course, queue.blocks.length), };
  const remainingHours = queue.blocks
    .filter((item) => {
      const itemDeadline = realBlockDeadline(item);
      return itemDeadline !== undefined && itemDeadline <= deadline;
    })
    .reduce((total, item) => total + item.hours, 0);
  return {
    hard: deadlinePressure(remainingHours, capacityBetween(date, deadline, settings.maxDailyHours, today, todayCapacity, capacityRules)),
    dependencyUnlock: dependencyUnlockPressure(queue.course, remainingHours),
  };
}

function dependencyUnlockPressure(course: Course, remaining: number) {
  return course.dependsOnIds?.length || course.dependsOnId ? remaining : 0;
}

function scoreQueue(
  queue: CourseWorkQueue,
  queues: Map<string, CourseWorkQueue>,
  date: string,
  settings: StudyState["settings"] & { maxDailyHours: number },
  today: string,
  todayCapacity: number,
  capacityRules: CapacityRules,
  scheduledToday: Map<string, number>,
) {
  const course = queue.course;
  const block = queue.blocks[0];
  const deadline = realBlockDeadline(block);
  const priorityScore = { high: 300, medium: 180, low: 80 }[course.priority];
  const orderScore = Math.max(0, 260 - planningOrder(course, new Map([[course.id, queue.originalIndex + 1]])) * 35);
  const repeatedTodayPenalty = (scheduledToday.get(course.id) ?? 0) * 35;
  const studyScore = block.stage === "study" ? 420 : 0;
  const customDeadlineScore = block.customDeadline ? 600 : 0;

  if (!deadline) {
    return studyScore + priorityScore + orderScore + customDeadlineScore - repeatedTodayPenalty;
  }

  const remainingHours = queue.blocks
    .filter((item) => {
      const itemDeadline = realBlockDeadline(item);
      return itemDeadline !== undefined && itemDeadline <= deadline;
    })
    .reduce((total, item) => total + item.hours, 0);
  const capacityUntilDeadline = capacityBetween(date, deadline, settings.maxDailyHours, today, todayCapacity, capacityRules);
  const latestSafeStart = latestSafeStartDate(deadline, remainingHours, settings.maxDailyHours, today, todayCapacity, capacityRules);
  const pressure = deadlinePressure(remainingHours, capacityUntilDeadline);
  const pressureScore = pressure >= PRESSURE_URGENT
    ? 12_000 + pressure * 2_500
    : pressure >= PRESSURE_WATCH
      ? 5_000 + pressure * 1_600
      : pressure >= PRESSURE_SAFE
        ? 1_800 + pressure * 900
        : pressure * 350;
  const safeStartScore = date >= latestSafeStart ? 2_500 : 0;
  const dueSoonScore = 350 / Math.max(daysBetween(date, deadline), 1);
  const prepScore = block.stage === "revision" ? revisionPriorityScore(block, date, queues, settings, today, todayCapacity, capacityRules) : 0;

  return pressureScore + safeStartScore + dueSoonScore + studyScore + prepScore + priorityScore + orderScore + customDeadlineScore - repeatedTodayPenalty;
}

function revisionPriorityScore(
  block: WorkBlock,
  date: string,
  queues: Map<string, CourseWorkQueue>,
  settings: StudyState["settings"] & { maxDailyHours: number },
  today: string,
  todayCapacity: number,
  capacityRules: CapacityRules,
) {
  const examDate = block.course.examDate;
  if (!examDate || date < examPrepStartDate(examDate)) return -10_000;

  const urgentStudyExists = [...queues.values()].some((queue) => {
    const nextBlock = queue.blocks[0];
    if (!nextBlock || nextBlock.stage !== "study") return false;
    const deadline = realBlockDeadline(nextBlock);
    if (!deadline) return false;
    const remainingHours = queue.blocks
      .filter((item) => item.stage === "study" && realBlockDeadline(item) === deadline)
      .reduce((total, item) => total + item.hours, 0);
    const safeStart = latestSafeStartDate(deadline, remainingHours, settings.maxDailyHours, today, todayCapacity, capacityRules);
    return date >= safeStart || capacityBetween(date, deadline, settings.maxDailyHours, today, todayCapacity, capacityRules) <= remainingHours + block.hours;
  });

  const mockPenalty = block.type === "mock" && urgentStudyExists ? -8_000 : 0;
  const examSoonScore = 900 / Math.max(daysBetween(date, examDate), 1);
  return examSoonScore + mockPenalty;
}

function makeTaskFromBlock(block: WorkBlock, date: string): StudyTask {
  const stableId = makeTaskStableId(block);
  return {
    id: `auto-${date}-${stableId}`,
    date,
    deadline: block.deadline,
    customDeadline: block.customDeadline,
    title: block.title,
    subject: block.course.name,
    courseId: block.course.id,
    lectureNumbers: block.type === "lecture" ? lectureNumbersFromTitle(block.title) : undefined,
    studyMethodId: block.method?.id,
    studyMethodItem: block.methodItem,
    type: block.type,
    phase: "Auto plan",
    estimatedHours: block.hours,
    completed: false,
    autoGenerated: true,
    origin: "generated",
    planningOrder: block.sequence,
    parentTaskId: block.parentTaskId,
    segmentNumber: block.segmentNumber,
    segmentCount: block.segmentCount,
  };
}

function hasRemainingWork(queues: Map<string, CourseWorkQueue>) {
  return [...queues.values()].some((queue) => queue.blocks.length > 0);
}

function dependenciesSatisfied(
  course: Course,
  queues: Map<string, CourseWorkQueue>,
  date: string,
  dependencyCompletionDates: Map<string, string>,
) {
  return getDependencyIds(course).every((dependencyId) => {
    const dependencyQueue = queues.get(dependencyId);
    if (!dependencyQueue) return true;
    if (dependencyQueue.blocks.some((block) => block.stage === "study")) return false;
    const completedOn = dependencyCompletionDates.get(dependencyId);
    return !completedOn || completedOn < date;
  });
}

function realBlockDeadline(block: WorkBlock) {
  if (block.stage === "revision") return block.hardDeadline ?? block.deadline;
  return block.deadline;
}

function latestRealDeadline(courses: Course[]) {
  return courses
    .flatMap((course) => [course.targetFinishDate, course.examDate])
    .filter((date): date is string => Boolean(date))
    .sort()
    .at(-1);
}

function capacityBetween(
  startDate: string,
  endDate: string,
  maxDailyHours: number,
  today: string,
  todayCapacity: number,
  capacityRules: CapacityRules,
) {
  return dateRange(startDate, endDate).reduce(
    (total, date) => total + capacityForDate(date, maxDailyHours, today, todayCapacity, capacityRules),
    0,
  );
}

function latestSafeStartDate(
  deadline: string,
  remainingHours: number,
  maxDailyHours: number,
  today: string,
  todayCapacity: number,
  capacityRules: CapacityRules,
) {
  let accumulated = 0;
  let cursor = deadline;
  let guard = 0;

  while (cursor >= today && guard < 800) {
    accumulated += capacityForDate(cursor, maxDailyHours, today, todayCapacity, capacityRules);
    if (accumulated >= remainingHours) return cursor;
    cursor = addDays(cursor, -1);
    guard += 1;
  }

  return today;
}

function daysBetween(start: string, end: string) {
  const startTime = new Date(`${start}T00:00:00`).getTime();
  const endTime = new Date(`${end}T00:00:00`).getTime();
  return Math.ceil((endTime - startTime) / (1000 * 60 * 60 * 24));
}

function studyHoursForCourse(course: Course, completedNumbers: Set<number>, completedStudyItems: Map<string, Set<number>>) {
  return getStudyMethods(course).reduce((total, method) => {
    const completedItems = completedStudyItems.get(method.id) ?? new Set<number>();
    let remainingItems = 0;
    for (let item = 1; item <= method.totalItems; item += 1) {
      const completed = method.id === "lectures"
        ? completedNumbers.has(item)
        : completedItems.has(item);
      if (!completed) remainingItems += 1;
    }
    return total + remainingItems * method.hoursPerItem;
  }, 0);
}

function resolveEffectiveStudyDeadlines(
  courses: Course[],
  studyHoursByCourse: Map<string, number>,
  settings: StudyState["settings"] & { maxDailyHours: number },
  today: string,
  todayCapacity: number,
  capacityRules: CapacityRules,
) {
  const deadlines = new Map<string, string>();
  for (const course of courses) {
    const ownDeadline = course.targetFinishDate ?? course.examDate;
    if (ownDeadline) deadlines.set(course.id, ownDeadline);
  }

  for (let pass = 0; pass < courses.length + 2; pass += 1) {
    let changed = false;
    for (const course of courses) {
      const courseDeadline = deadlines.get(course.id);
      if (!courseDeadline) continue;

      const courseStudyHours = Math.max(studyHoursByCourse.get(course.id) ?? 0, 0.1);
      const latestCourseStart = latestSafeStartDate(
        courseDeadline,
        courseStudyHours,
        settings.maxDailyHours,
        today,
        todayCapacity,
        capacityRules,
      );
      const dependencyDeadline = addDays(latestCourseStart, -1);

      for (const dependencyId of getDependencyIds(course)) {
        const current = deadlines.get(dependencyId);
        if (!current || dependencyDeadline < current) {
          deadlines.set(dependencyId, dependencyDeadline);
          changed = true;
        }
      }
    }
    if (!changed) break;
  }

  return deadlines;
}

function createStudyBlocks(
  course: Course,
  earliestDate: string,
  completedNumbers: Set<number>,
  completedStudyItems: Map<string, Set<number>>,
  deadline?: string,
  taskDeadlines = new Map<string, string>(),
  taskOrders = new Map<string, number>(),
): WorkBlock[] {
  const blocks: WorkBlock[] = [];
  const methods = getStudyMethods(course);
  let globalSequence = 0;

  for (const [methodIndex, method] of methods.entries()) {
    const completedItems = completedStudyItems.get(method.id) ?? new Set<number>();
    const orderMode = taskOrderMode(method.taskType);
    let item = 1;
    while (item <= method.totalItems) {
      globalSequence += 1;
      const completed = method.id === "lectures"
        ? completedNumbers.has(item)
        : completedItems.has(item);
      if (completed) {
        item += 1;
        continue;
      }

      const title = method.taskType === "lecture" ? `${course.name} L${item}` : `${course.name} ${method.name} ${item}`;
      const overrideDeadline = taskDeadlines.get(taskDeadlineKey(course.id, method.id, item)) ?? taskDeadlines.get(blockKey(course.id, method.taskType, title));
      const overrideOrder = taskOrders.get(taskDeadlineKey(course.id, method.id, item)) ?? taskOrders.get(blockKey(course.id, method.taskType, title));
      const sequence = orderMode === "strict" ? 10_000 + methodIndex * 1_000 + item : overrideOrder ?? 10_000 + globalSequence;

      const baseBlock: WorkBlock = {
        course,
        method,
        title,
        type: method.taskType,
        stage: "study",
        hours: roundToOne(method.hoursPerItem),
        deadline: overrideDeadline ?? deadline,
        customDeadline: overrideDeadline,
        hardDeadline: overrideDeadline ?? deadline,
        earliestDate,
        sequence,
        methodItem: item,
        methodOrder: methodIndex + 1,
        itemNumber: item,
      };
      blocks.push(...splitBlockIfAllowed(baseBlock));
      item += 1;
    }
  }

  return blocks.sort((a, b) => a.sequence - b.sequence || a.methodOrder - b.methodOrder || a.itemNumber - b.itemNumber || makeTaskStableId(a).localeCompare(makeTaskStableId(b)));
}

function createRevisionBlocks(course: Course, earliestDate: string): WorkBlock[] {
  const courseDeadline = course.targetFinishDate ?? course.examDate ?? addDays(earliestDate, 365);
  const revisionDeadline = course.examDate ? addDays(course.examDate, -1) : courseDeadline;
  const revisionStart = course.examDate
    ? maxDate(earliestDate, examPrepStartDate(course.examDate))
    : maxDate(earliestDate, addDays(courseDeadline, 1));
  const planningDeadline = preferredRevisionDeadline(course, revisionStart, revisionDeadline);
  return [
    {
      course,
      title: `${course.name} revision block 1`,
      type: "revision",
      stage: "revision",
      hours: 2,
      deadline: planningDeadline,
      hardDeadline: revisionDeadline,
      earliestDate: revisionStart,
      sequence: course.totalLectures + 1,
      methodOrder: 9_000,
      itemNumber: 1,
    },
    {
      course,
      title: `${course.name} revision block 2`,
      type: "revision",
      stage: "revision",
      hours: 2,
      deadline: planningDeadline,
      hardDeadline: revisionDeadline,
      earliestDate: revisionStart,
      sequence: course.totalLectures + 2,
      methodOrder: 9_000,
      itemNumber: 2,
    },
    {
      course,
      title: `${course.name} mock exam`,
      type: "mock",
      stage: "revision",
      hours: 3,
      deadline: planningDeadline,
      hardDeadline: revisionDeadline,
      earliestDate: revisionStart,
      sequence: course.totalLectures + 3,
      methodOrder: 9_001,
      itemNumber: 1,
    },
  ];
}

function splitBlockIfAllowed(block: WorkBlock): WorkBlock[] {
  if (!isSplittableTask(block.type) || block.hours <= Math.max(MIN_SPLIT_BLOCK_HOURS, 1)) return [block];
  const preferredSize = Math.max(MIN_SPLIT_BLOCK_HOURS, Math.min(1, block.hours));
  const segmentCount = Math.ceil(block.hours / preferredSize);
  if (segmentCount <= 1) return [block];

  const wholeSegments = Math.floor(block.hours / preferredSize);
  const remainder = roundToOne(block.hours - wholeSegments * preferredSize);
  const segmentHours = Array.from({ length: wholeSegments }, () => preferredSize);
  if (remainder >= MIN_SPLIT_BLOCK_HOURS) segmentHours.push(remainder);
  else if (remainder > 0 && segmentHours.length) segmentHours[segmentHours.length - 1] = roundToOne(segmentHours[segmentHours.length - 1] + remainder);

  const actualSegmentCount = segmentHours.length;
  return segmentHours.map((hours, index) => ({
    ...block,
    title: actualSegmentCount === 1 ? block.title : `${block.title} (${index + 1}/${actualSegmentCount})`,
    hours,
    sequence: block.sequence + index / 100,
    parentTaskId: `${block.course.id}:${block.method?.id ?? block.type}:${block.itemNumber}`,
    segmentNumber: index + 1,
    segmentCount: actualSegmentCount,
  }));
}

function isSplittableTask(type: TaskType) {
  return ["coding", "recap", "revision", "summary"].includes(type);
}

function taskOrderMode(type: TaskType): "strict" | "loose" | "free" {
  if (type === "lecture" || type === "mock") return "strict";
  if (type === "coding" || type === "summary" || type === "recap") return "loose";
  return "free";
}

function examPrepStartDate(examDate: string) {
  return addDays(examDate, -EXAM_PREP_WINDOW_DAYS);
}

function findMinimumDailyLimit(
  state: StudyState,
  options: { today: string; endDate?: string; holidays?: string[]; customStudyHours?: Array<{ date: string; hours: number }>; restrictedDays?: Array<{ date: string; maxHours: number }>; minDailyHours: number; maxDailyHours: number },
) {
  for (let cap = options.minDailyHours; cap <= options.maxDailyHours; cap += 0.5) {
    const plan = autoPlanSchedule(state, {
      today: options.today,
      maxDailyHours: cap,
      endDate: options.endDate,
      holidays: options.holidays,
      customStudyHours: options.customStudyHours,
      restrictedDays: options.restrictedDays,
      ignoreTodayClock: true,
    });
    if (validatePlannedState(plan, options.today).every((issue) => issue.severity !== "error") && !planRangeMiss(plan)) return cap;
  }

  return undefined;
}

function recoverySuggestion(state: StudyState, options: PlanOptions) {
  const overdueGenerated = state.tasks.filter((task) =>
    !task.completed &&
    task.date < options.today &&
    task.estimatedHours > 0 &&
    (task.autoGenerated || task.origin === "generated") &&
    !task.locked &&
    !task.dirty
  );
  const missedHours = roundToOne(overdueGenerated.reduce((total, task) => total + task.estimatedHours, 0));
  if (missedHours <= 0) return undefined;

  const settings = state.settings;
  const rules: CapacityRules = {
    today: options.today,
    todayCapacity: options.maxDailyHours,
    holidays: new Set(options.holidays ?? settings?.holidays ?? []),
    customStudyHours: new Map((options.customStudyHours ?? settings?.customStudyHours ?? migrateRestrictedDays(options.restrictedDays ?? settings?.restrictedDays)).map((day) => [day.date, day.hours])),
  };
  const recoveryDays: Array<{ date: string; extra: number }> = [];
  let remaining = missedHours;
  let cursor = options.today;
  for (let guard = 0; guard < 14 && recoveryDays.length < 7 && remaining > 0; guard += 1) {
    const capacity = capacityForDate(cursor, options.maxDailyHours, options.today, options.maxDailyHours, rules);
    if (capacity > 0) {
      const extra = Math.min(2, remaining);
      recoveryDays.push({ date: cursor, extra });
      remaining = roundToOne(remaining - extra);
    }
    cursor = addDays(cursor, 1);
  }
  if (remaining > 0) return undefined;

  const issue: PlannerValidationIssue = {
    type: "recovery",
    severity: "warning",
    date: options.today,
    message: `Missed work created a temporary ${missedHours}h backlog.`,
    blockers: overdueGenerated.slice(0, 5).map((task) => task.title),
    suggestions: [
      `Keep the normal ${options.maxDailyHours}h daily cap and add ${roundToOne(missedHours / recoveryDays.length)}h/day over the next ${recoveryDays.length} available days.`,
      `Or add one custom ${roundToOne(options.maxDailyHours + missedHours)}h study day if that feels realistic.`,
    ],
  };

  return {
    issue,
    message: `You missed ${missedHours}h of generated work. Your normal ${options.maxDailyHours}h/day cap stays unchanged; easiest recovery is adding about ${roundToOne(missedHours / recoveryDays.length)}h/day across the next ${recoveryDays.length} available days.`,
  };
}

function traceTask(task: StudyTask) {
  return {
    id: task.id,
    date: task.date,
    title: task.title,
    courseId: task.courseId,
    type: task.type,
    hours: task.estimatedHours,
    completed: task.completed,
    origin: task.origin,
    autoGenerated: task.autoGenerated,
    locked: task.locked,
    dirty: task.dirty,
    deadline: task.deadline,
    customDeadline: task.customDeadline,
    studyMethodId: task.studyMethodId,
    studyMethodItem: task.studyMethodItem,
    parentTaskId: task.parentTaskId,
    segmentNumber: task.segmentNumber,
    segmentCount: task.segmentCount,
  };
}

function groupHoursByDate(tasks: StudyTask[]) {
  const hours = new Map<string, number>();
  for (const task of tasks) {
    hours.set(task.date, roundToOne((hours.get(task.date) ?? 0) + task.estimatedHours));
  }
  return hours;
}

function planRangeMiss(state: StudyState) {
  const rangeEnd = state.settings?.planEndDate;
  if (!rangeEnd) return undefined;
  const latestScheduledDate = state.tasks
    .filter((task) => task.autoGenerated)
    .map((task) => task.date)
    .sort()
    .at(-1);
  if (!latestScheduledDate || latestScheduledDate <= rangeEnd) return undefined;
  return { rangeEnd, latestScheduledDate };
}

export function validatePlannedState(state: StudyState, today: string): PlannerValidationIssue[] {
  const issues: PlannerValidationIssue[] = [];
  const settings = state.settings;
  const maxDailyHours = settings?.maxDailyHours ?? 8;
  const rules: CapacityRules = {
    today,
    todayCapacity: maxDailyHours,
    holidays: new Set(settings?.holidays ?? []),
    customStudyHours: new Map((settings?.customStudyHours ?? migrateRestrictedDays(settings?.restrictedDays)).map((day) => [day.date, day.hours])),
  };
  const tasks = state.tasks.filter((task) => task.type !== "exam" && task.type !== "rest");
  const tasksByCourse = new Map<string, StudyTask[]>();
  const dailyHours = new Map<string, number>();
  const courseIds = new Set(state.courses.map((course) => course.id));

  for (const graphIssue of dependencyGraphIssues(state.courses)) {
    issues.push({
      type: "dependency",
      severity: "error",
      courseId: graphIssue.courseId,
      message: graphIssue.message,
      blockers: graphIssue.path,
      suggestions: ["Fix the dependency chain before generating a plan."],
    });
  }

  for (const dataIssue of corruptedInputIssues(state, today)) {
    issues.push(dataIssue);
  }

  for (const task of tasks) {
    if (task.courseId && !courseIds.has(task.courseId)) {
      issues.push({
        type: "data",
        severity: "warning",
        date: task.date,
        taskId: task.id,
        courseId: task.courseId,
        message: `${task.title} references a deleted course and will be ignored by course planning.`,
        suggestions: ["Relink the task to an existing course or remove it."],
      });
    }
    dailyHours.set(task.date, roundToOne((dailyHours.get(task.date) ?? 0) + task.estimatedHours));
    if (task.courseId) {
      const courseTasks = tasksByCourse.get(task.courseId) ?? [];
      courseTasks.push(task);
      tasksByCourse.set(task.courseId, courseTasks);
    }
    if (rules.holidays.has(task.date)) {
      issues.push({
        type: "holiday",
        severity: "error",
        date: task.date,
        taskId: task.id,
        courseId: task.courseId,
        message: `${task.title} is scheduled on a holiday (${task.date}).`,
      });
    }
    const taskDeadline = task.customDeadline ?? task.deadline;
    if (taskDeadline && task.date > taskDeadline) {
      issues.push({
        type: "deadline",
        severity: "error",
        date: task.date,
        taskId: task.id,
        courseId: task.courseId,
        message: `${task.title} is scheduled on ${task.date}, after its ${taskDeadline} deadline.`,
      });
    }
  }

  for (const [date, hours] of dailyHours) {
    const capacity = capacityForDate(date, maxDailyHours, today, maxDailyHours, rules);
    if (hours > capacity) {
      issues.push({
        type: "capacity",
        severity: "error",
        date,
        message: `${date} has ${roundToOne(hours)}h planned, above the ${roundToOne(capacity)}h available.`,
      });
    }
  }

  const coreFinishByCourse = new Map<string, string>();
  const coreStartByCourse = new Map<string, string>();
  for (const course of state.courses) {
    const courseTasks = (tasksByCourse.get(course.id) ?? []).sort((a, b) => a.date.localeCompare(b.date) || (a.planningOrder ?? 0) - (b.planningOrder ?? 0));
    const coreTasks = courseTasks.filter((task) => !["revision", "mock"].includes(task.type));
    const coreFinish = coreTasks.map((task) => task.date).sort().at(-1);
    const coreStart = coreTasks.map((task) => task.date).sort().at(0);
    if (coreFinish) coreFinishByCourse.set(course.id, coreFinish);
    if (coreStart) coreStartByCourse.set(course.id, coreStart);

    const effectiveDeadline = course.targetFinishDate ?? (course.examDate ? addDays(course.examDate, -EXAM_PREP_WINDOW_DAYS) : undefined);
    if (effectiveDeadline && coreFinish && coreFinish > effectiveDeadline) {
      issues.push({
        type: "deadline",
        severity: "error",
        date: coreFinish,
        courseId: course.id,
        message: `${course.name} finishes on ${coreFinish}, after its ${effectiveDeadline} target.`,
      });
    }

    const seenMethodDates = new Map<string, string>();
    const seenGeneratedKeys = new Set<string>();
    for (const task of coreTasks) {
      const methodKey = task.studyMethodId ?? (task.type === "lecture" ? "lectures" : task.type);
      const itemKey = `${course.id}:${methodKey}:${task.studyMethodItem ?? task.title}:${task.parentTaskId ?? ""}:${task.segmentNumber ?? ""}`;
      if ((task.autoGenerated || task.origin === "generated") && seenGeneratedKeys.has(itemKey)) {
        issues.push({
          type: "duplicate",
          severity: "error",
          date: task.date,
          taskId: task.id,
          courseId: course.id,
          message: `${task.title} was generated more than once.`,
          suggestions: ["Regenerate the plan after clearing duplicate generated tasks."],
        });
      }
      seenGeneratedKeys.add(itemKey);

      const previousDate = seenMethodDates.get(methodKey);
      if (previousDate && task.date < previousDate) {
        issues.push({
          type: "order",
          severity: "error",
          date: task.date,
          taskId: task.id,
          courseId: course.id,
          message: `${task.title} is out of sequence for ${course.name}.`,
        });
      }
      seenMethodDates.set(methodKey, task.date);
    }

    for (const issue of strictSequenceIssues(course, coreTasks)) {
      issues.push(issue);
    }

    const prepStart = course.examDate ? examPrepStartDate(course.examDate) : undefined;
    for (const task of courseTasks.filter((item) => item.type === "revision" || item.type === "mock")) {
      if (prepStart && task.date < prepStart) {
        issues.push({
          type: "revision",
          severity: "error",
          date: task.date,
          taskId: task.id,
          courseId: course.id,
          message: `${task.title} is before the exam prep window starts on ${prepStart}.`,
        });
      }
      if (task.type === "mock" && coreFinish && task.date <= coreFinish) {
        issues.push({
          type: "revision",
          severity: "error",
          date: task.date,
          taskId: task.id,
          courseId: course.id,
          message: `${task.title} is before ${course.name} core work is complete.`,
        });
      }
    }
  }

  for (const course of state.courses) {
    const start = coreStartByCourse.get(course.id);
    if (!start) continue;
    for (const dependencyId of getDependencyIds(course)) {
      const dependencyFinish = coreFinishByCourse.get(dependencyId);
      if (dependencyFinish && start <= dependencyFinish) {
        issues.push({
          type: "dependency",
          severity: "error",
          date: start,
          courseId: course.id,
          message: `${course.name} starts on ${start} before its prerequisite finishes on ${dependencyFinish}.`,
        });
      }
    }
  }

  return issues.sort(compareIssueSeverity);
}

function planningOrder(course: Course, originalOrder: Map<string, number>) {
  return course.planningOrder ?? originalOrder.get(course.id) ?? 9999;
}

function dependencyGraphIssues(courses: Course[]): DependencyGraphIssue[] {
  const issues: DependencyGraphIssue[] = [];
  const byId = new Map(courses.map((course) => [course.id, course]));

  for (const course of courses) {
    for (const dependencyId of getDependencyIds(course)) {
      if (!byId.has(dependencyId)) {
        issues.push({
          type: "missing",
          courseId: course.id,
          message: `${course.name} depends on a missing or deleted course. Fix the dependency before planning.`,
          path: [course.name, dependencyId],
        });
      }
    }
  }

  const visiting = new Set<string>();
  const visited = new Set<string>();
  const stack: string[] = [];
  const cycleKeys = new Set<string>();

  function visit(courseId: string) {
    if (visiting.has(courseId)) {
      const cycleStart = stack.indexOf(courseId);
      const cycleIds = [...stack.slice(Math.max(cycleStart, 0)), courseId];
      const key = cycleIds.join(">");
      if (!cycleKeys.has(key)) {
        cycleKeys.add(key);
        const path = cycleIds.map((id) => byId.get(id)?.name ?? id);
        const first = cycleIds[0];
        issues.push({
          type: "cycle",
          courseId: first,
          message: `Circular dependency detected: ${path.join(" -> ")}.`,
          path,
          courseIds: cycleIds,
        });
      }
      return;
    }
    if (visited.has(courseId)) return;
    const course = byId.get(courseId);
    if (!course) return;
    visiting.add(courseId);
    stack.push(courseId);
    for (const dependencyId of getDependencyIds(course)) visit(dependencyId);
    stack.pop();
    visiting.delete(courseId);
    visited.add(courseId);
  }

  for (const course of courses) visit(course.id);
  return issues;
}

function corruptedInputIssues(state: StudyState, today: string): PlannerValidationIssue[] {
  const issues: PlannerValidationIssue[] = [];
  const seenCourses = new Set<string>();
  const seenTasks = new Set<string>();

  for (const course of state.courses) {
    if (seenCourses.has(course.id)) {
      issues.push({
        type: "data",
        severity: "error",
        courseId: course.id,
        message: `Duplicate course ID detected: ${course.id}.`,
        suggestions: ["Rename or remove the duplicate course before planning."],
      });
    }
    seenCourses.add(course.id);
    if (course.completedLectures > course.totalLectures) {
      issues.push({
        type: "data",
        severity: "warning",
        courseId: course.id,
        message: `${course.name} has more completed items than total items; progress is clamped for planning.`,
      });
    }
    if (course.targetFinishDate && course.targetFinishDate < today) {
      issues.push({
        type: "deadline",
        severity: "warning",
        courseId: course.id,
        date: course.targetFinishDate,
        message: `${course.name} has a target date in the past.`,
        suggestions: ["Move the target date or generate a rescue plan."],
      });
    }
    if (course.examDate && course.targetFinishDate && course.examDate < course.targetFinishDate) {
      issues.push({
        type: "deadline",
        severity: "warning",
        courseId: course.id,
        date: course.examDate,
        message: `${course.name} has an exam before its target finish date.`,
        suggestions: ["Move the target finish date before the exam date."],
      });
    }
  }

  for (const task of state.tasks) {
    if (seenTasks.has(task.id)) {
      issues.push({
        type: "duplicate",
        severity: "error",
        taskId: task.id,
        date: task.date,
        message: `Duplicate task ID detected: ${task.id}.`,
        suggestions: ["Remove or regenerate duplicate tasks."],
      });
    }
    seenTasks.add(task.id);
    if (!isDateKey(task.date)) {
      issues.push({
        type: "data",
        severity: "error",
        taskId: task.id,
        message: `${task.title} has an invalid planned date.`,
      });
    }
    if (task.estimatedHours < 0 || !Number.isFinite(task.estimatedHours)) {
      issues.push({
        type: "data",
        severity: "error",
        taskId: task.id,
        message: `${task.title} has invalid hours.`,
      });
    }
  }

  return issues;
}

function strictSequenceIssues(course: Course, coreTasks: StudyTask[]): PlannerValidationIssue[] {
  const issues: PlannerValidationIssue[] = [];
  const byMethod = new Map<string, StudyTask[]>();
  for (const task of coreTasks) {
    const methodKey = task.studyMethodId ?? (task.type === "lecture" ? "lectures" : task.type);
    const tasks = byMethod.get(methodKey) ?? [];
    tasks.push(task);
    byMethod.set(methodKey, tasks);
  }

  for (const [methodKey, tasks] of byMethod) {
    const method = getStudyMethods(course).find((item) => item.id === methodKey);
    const type = method?.taskType ?? (methodKey === "lectures" ? "lecture" : tasks[0]?.type);
    if (!type || taskOrderMode(type) !== "strict") continue;

    const ordered = [...tasks]
      .filter((task) => typeof task.studyMethodItem === "number")
      .sort((a, b) => (a.studyMethodItem ?? 0) - (b.studyMethodItem ?? 0));
    for (let index = 1; index < ordered.length; index += 1) {
      const previous = ordered[index - 1];
      const current = ordered[index];
      if ((current.studyMethodItem ?? 0) > (previous.studyMethodItem ?? 0) + 1 && !previous.completed) {
        issues.push({
          type: "order",
          severity: "error",
          date: current.date,
          taskId: current.id,
          courseId: course.id,
          message: `${current.title} skips earlier required work in ${course.name}.`,
          blockers: [previous.title],
          suggestions: ["Schedule the earlier task first or change this method to a loose/free order mode when that setting exists."],
        });
      }
      if (current.date < previous.date) {
        issues.push({
          type: "order",
          severity: "error",
          date: current.date,
          taskId: current.id,
          courseId: course.id,
          message: `${current.title} is scheduled before ${previous.title}, but this method is strict order.`,
          blockers: [previous.title],
        });
      }
    }
  }

  return issues;
}

function compareIssueSeverity(a: PlannerValidationIssue, b: PlannerValidationIssue) {
  const severityRank = { error: 0, warning: 1, info: 2 };
  return severityRank[a.severity] - severityRank[b.severity] ||
    (a.date ?? "9999-12-31").localeCompare(b.date ?? "9999-12-31") ||
    a.message.localeCompare(b.message);
}

function preferredRevisionDeadline(course: Course, earliestDate: string, hardDeadline: string) {
  return hardDeadline < earliestDate ? earliestDate : hardDeadline;
}

function dateRange(start: string, end: string) {
  if (start > end) return [];

  const dates: string[] = [];
  const cursor = new Date(`${start}T00:00:00`);
  const last = new Date(`${end}T00:00:00`);

  while (cursor <= last) {
    dates.push(dateKey(cursor));
    cursor.setDate(cursor.getDate() + 1);
  }

  return dates;
}

function maxDate(a: string, b: string) {
  return a > b ? a : b;
}

function isDateKey(value: string) {
  const match = value.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (!match) return false;
  const year = Number(match[1]);
  const month = Number(match[2]);
  const day = Number(match[3]);
  const date = new Date(year, month - 1, day);
  return date.getFullYear() === year && date.getMonth() === month - 1 && date.getDate() === day;
}

function capacityForDate(date: string, maxDailyHours: number, today: string, todayCapacity: number, rules: CapacityRules) {
  if (rules.holidays.has(date)) return 0;
  const base = date === today ? todayCapacity : maxDailyHours;
  const customHours = rules.customStudyHours.get(date);
  return customHours === undefined ? base : customHours;
}

function migrateRestrictedDays(days?: Array<{ date: string; maxHours: number }>) {
  return (days ?? []).map((day) => ({ date: day.date, hours: day.maxHours }));
}

function isGeneratedRestTask(task: StudyTask) {
  return task.type === "rest" && task.estimatedHours === 0 && (task.autoGenerated || /^rest$/i.test(task.title.trim()));
}

function shouldPreserveTaskForPlanning(task: StudyTask, today: string) {
  if (task.completed || task.type === "exam" || (task.type === "rest" && !isGeneratedRestTask(task))) return true;
  if (task.locked || task.dirty || task.origin === "manual" || (!task.autoGenerated && task.origin !== "generated")) return true;
  return Boolean(task.autoGenerated || task.origin === "generated") && task.date === today;
}

function deadlinePressure(requiredHours: number, availableHours: number) {
  if (requiredHours <= 0) return 0;
  if (availableHours <= 0) return Number.POSITIVE_INFINITY;
  return requiredHours / availableHours;
}

function slug(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function makeTaskStableId(block: WorkBlock) {
  return [
    block.course.id,
    block.method?.id ?? block.type,
    block.methodItem ?? block.itemNumber,
    block.segmentNumber ?? 0,
    slug(block.title),
  ].join("-");
}

function blockKey(courseId: string | undefined, type: TaskType, title: string) {
  return `${courseId ?? "general"}:${type}:${title}`;
}

function taskDeadlineKey(courseId: string, methodId: string, item: number) {
  return `${courseId}:${methodId}:${item}`;
}

function getTaskDeadlineOverrides(tasks: StudyTask[]) {
  const deadlines = new Map<string, string>();
  for (const task of tasks) {
    const deadline = task.customDeadline ?? task.deadline;
    if (!task.courseId || !deadline) continue;
    if (task.studyMethodId && task.studyMethodItem) {
      deadlines.set(taskDeadlineKey(task.courseId, task.studyMethodId, task.studyMethodItem), deadline);
    }
    deadlines.set(blockKey(task.courseId, task.type, task.title), deadline);
  }
  return deadlines;
}

function getTaskOrderOverrides(tasks: StudyTask[]) {
  const orders = new Map<string, number>();
  for (const task of tasks) {
    if (!task.courseId || typeof task.planningOrder !== "number" || !Number.isFinite(task.planningOrder)) continue;
    if (task.studyMethodId && task.studyMethodItem) {
      orders.set(taskDeadlineKey(task.courseId, task.studyMethodId, task.studyMethodItem), task.planningOrder);
    }
    orders.set(blockKey(task.courseId, task.type, task.title), task.planningOrder);
  }
  return orders;
}

function getDependencyIds(course: Course) {
  return course.dependsOnIds?.length ? course.dependsOnIds : course.dependsOnId ? [course.dependsOnId] : [];
}

function getStudyMethods(course: Course): StudyMethod[] {
  return course.studyMethods !== undefined
    ? course.studyMethods
    : [
        {
          id: "lectures",
          name: "Lecture",
          totalItems: course.totalLectures,
          completedItems: course.completedLectures,
          hoursPerItem: course.hoursPerLecture,
          taskType: "lecture",
        },
      ];
}

function getCompletedLectureNumbers(state: StudyState) {
  const result = new Map<string, Set<number>>();

  for (const course of state.courses) {
    const completed = new Set<number>();
    const baseline = Math.min(course.baselineCompletedLectures ?? course.completedLectures, course.totalLectures);
    for (let lecture = 1; lecture <= baseline; lecture += 1) {
      completed.add(lecture);
    }
    result.set(course.id, completed);
  }

  for (const task of state.tasks) {
    if (!task.completed || !task.courseId) continue;
    const completed = result.get(task.courseId);
    if (!completed) continue;
    if (task.type !== "lecture") continue;
    const lectureNumbers = task.lectureNumbers?.length ? task.lectureNumbers : lectureNumbersFromTitle(task.title);
    for (const lecture of lectureNumbers) {
      completed.add(lecture);
    }
  }

  return result;
}

function getCompletedStudyItems(state: StudyState) {
  const result = new Map<string, Map<string, Set<number>>>();

  for (const course of state.courses) {
    const byMethod = new Map<string, Set<number>>();
    for (const method of getStudyMethods(course)) {
      const completed = new Set<number>();
      for (let item = 1; item <= Math.min(method.completedItems, method.totalItems); item += 1) {
        completed.add(item);
      }
      byMethod.set(method.id, completed);
    }
    result.set(course.id, byMethod);
  }

  for (const task of state.tasks) {
    if (!task.completed || !task.courseId || !task.studyMethodId || !task.studyMethodItem) continue;
    const byMethod = result.get(task.courseId);
    const completed = byMethod?.get(task.studyMethodId);
    completed?.add(task.studyMethodItem);
    const titleItem = task.title.match(/(\d+)\s*$/)?.[1];
    if (titleItem) completed?.add(Number(titleItem));
  }

  return result;
}
