import { addDays, dateKey, lectureNumbersFromTitle, PLAN_START_DATE, projectedCourseFinishDate, roundToOne } from "./schedule";
import type { Course, PlannerCapacityWarning, StudyMethod, StudyState, StudyTask, TaskType } from "./types";

const priorityWeight = {
  high: 0,
  medium: 1,
  low: 2,
};

const EXAM_PREP_WINDOW_DAYS = 7;

type PlanOptions = {
  today: string;
  maxDailyHours: number;
  now?: Date;
  ignoreTodayClock?: boolean;
  endDate?: string;
  holidays?: string[];
  customStudyHours?: Array<{ date: string; hours: number }>;
  restrictedDays?: Array<{ date: string; maxHours: number }>;
};

type CapacityRules = {
  today: string;
  todayCapacity: number;
  holidays: Set<string>;
  customStudyHours: Map<string, number>;
};

type WorkBlock = {
  course: Course;
  method?: StudyMethod;
  title: string;
  type: TaskType;
  stage: "study" | "revision";
  hours: number;
  deadline?: string;
  customDeadline?: string;
  hardDeadline?: string;
  earliestDate: string;
  sequence: number;
  methodItem?: number;
};

type CourseWorkQueue = {
  course: Course;
  blocks: WorkBlock[];
  originalIndex: number;
};

export function createCourseId(name: string) {
  return name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

export function autoPlanSchedule(state: StudyState, options: PlanOptions): StudyState {
  const today = maxDate(options.today, state.settings?.startDate ?? PLAN_START_DATE);
  const settings = {
    ...state.settings,
    autoPlan: state.settings?.autoPlan ?? true,
    autoPlanIntervalHours: state.settings?.autoPlanIntervalHours ?? 24,
    maxDailyHours: options.maxDailyHours,
    startDate: state.settings?.startDate ?? PLAN_START_DATE,
    planEndDate: options.endDate ?? state.settings?.planEndDate,
    holidays: options.holidays ?? state.settings?.holidays ?? [],
    customStudyHours: options.customStudyHours ?? state.settings?.customStudyHours ?? migrateRestrictedDays(options.restrictedDays ?? state.settings?.restrictedDays),
    restrictedDays: options.restrictedDays ?? state.settings?.restrictedDays ?? [],
    lastAutoPlanDate: today,
    lastAutoPlanAt: new Date().toISOString(),
    defaultTaskHours: state.settings?.defaultTaskHours ?? 1,
    warningThresholdHours: state.settings?.warningThresholdHours ?? 8,
    showCompletedTasks: state.settings?.showCompletedTasks ?? true,
    weekStartsOn: state.settings?.weekStartsOn ?? "monday",
    reminderTime: state.settings?.reminderTime ?? "00:00",
    lateNightPromptEnabled: state.settings?.lateNightPromptEnabled ?? true,
    lateNightPromptAfterHour: state.settings?.lateNightPromptAfterHour ?? 23,
    lateNightMaxExtensionHour: state.settings?.lateNightMaxExtensionHour ?? 6,
    studyDayOverride: state.settings?.studyDayOverride,
    language: state.settings?.language ?? "en",
    theme: state.settings?.theme ?? "razor",
  };
  const todayCapacity = options.maxDailyHours;
  const capacityRules: CapacityRules = {
    today,
    todayCapacity,
    holidays: new Set(settings.holidays),
    customStudyHours: new Map(settings.customStudyHours.map((day) => [day.date, day.hours])),
  };

  const preservedTasks = state.tasks.filter(
    (task) => task.completed || task.type === "exam" || (task.type === "rest" && !isGeneratedRestTask(task)),
  );
  const generatedTasks: StudyTask[] = [];
  const dailyHours = new Map<string, number>();

  for (const task of preservedTasks) {
    dailyHours.set(task.date, roundToOne((dailyHours.get(task.date) ?? 0) + task.estimatedHours));
  }

  const completedGeneratedTitles = new Set(
    preservedTasks
      .filter((task) => task.autoGenerated && task.completed)
      .map((task) => blockKey(task.courseId, task.type, task.title)),
  );
  const completedLectureNumbers = getCompletedLectureNumbers(state);
  const completedStudyItems = getCompletedStudyItems(state);
  const taskDeadlines = getTaskDeadlineOverrides(state.tasks);
  const taskOrders = getTaskOrderOverrides(state.tasks);
  schedulePriorityAwareBlocks({
    courses: state.courses,
    completedLectureNumbers,
    completedStudyItems,
    completedGeneratedTitles,
    taskDeadlines,
    taskOrders,
    generatedTasks,
    dailyHours,
    settings,
    today,
    todayCapacity,
    capacityRules,
  });

  const examTasks = state.courses
    .filter((course) => course.hasExam && course.examDate)
    .filter((course) => !preservedTasks.some((task) => task.type === "exam" && task.courseId === course.id))
    .map((course) => ({
      id: `exam-${course.id}-${course.examDate}`,
      date: course.examDate as string,
      title: `${course.name} exam`,
      subject: course.name,
      courseId: course.id,
      type: "exam" as const,
      phase: "Deadline",
      estimatedHours: 0,
      completed: false,
    }));

  return {
    ...state,
    settings,
    tasks: [...preservedTasks, ...generatedTasks, ...examTasks].sort((a, b) => a.date.localeCompare(b.date)),
  };
}

export function plannerCapacityWarning(state: StudyState, options: PlanOptions): PlannerCapacityWarning | undefined {
  const currentPlan = autoPlanSchedule(state, { ...options, ignoreTodayClock: true });
  const rangeMiss = planRangeMiss(currentPlan);
  const capacityMiss = planCapacityMiss(currentPlan, options.today);
  const currentMiss = planDeadlineMiss(currentPlan);
  if (!currentMiss && !rangeMiss && !capacityMiss) return undefined;

  const suggestedDailyLimit = findMinimumDailyLimit(state, {
    today: options.today,
    endDate: options.endDate,
    holidays: options.holidays,
    customStudyHours: options.customStudyHours,
    restrictedDays: options.restrictedDays,
    minDailyHours: 1,
    maxDailyHours: 24,
  });

  if (suggestedDailyLimit !== undefined && suggestedDailyLimit <= options.maxDailyHours) {
    return undefined;
  }

  return {
    currentDailyLimit: options.maxDailyHours,
    suggestedDailyLimit,
    latestScheduledDate: currentMiss?.latestScheduledDate ?? rangeMiss?.latestScheduledDate ?? capacityMiss?.date ?? options.today,
    severity: "deadline",
    message: rangeMiss
      ? `This plan needs work after ${rangeMiss.rangeEnd}. Easiest fix: extend the range to ${rangeMiss.latestScheduledDate} or raise the daily cap.`
      : capacityMiss && suggestedDailyLimit
        ? `Raise the daily cap to ${suggestedDailyLimit}h so ${capacityMiss.date} stays within your daily limit.`
        : suggestedDailyLimit && currentMiss
        ? `This plan finishes ${currentMiss.courseName} on ${currentMiss.latestScheduledDate}, after its ${currentMiss.deadline} deadline. Raise the daily cap to ${suggestedDailyLimit}h to finish on time.`
        : "The current workload cannot fit before every deadline, even with a 24h daily cap.",
  };
}

export function hoursUntilNextRollover(now = new Date(), rolloverHour = 0) {
  const nextRollover = new Date(now);
  nextRollover.setHours(rolloverHour, 0, 0, 0);
  if (nextRollover <= now) nextRollover.setDate(nextRollover.getDate() + 1);
  return Math.max(roundToOne((nextRollover.getTime() - now.getTime()) / (1000 * 60 * 60)), 0);
}

export function getTodayPlanningCapacity(maxDailyHours: number, now = new Date()) {
  hoursUntilNextRollover(now);
  return roundToOne(maxDailyHours);
}

function schedulePriorityAwareBlocks({
  courses,
  completedLectureNumbers,
  completedStudyItems,
  completedGeneratedTitles,
  taskDeadlines,
  taskOrders,
  generatedTasks,
  dailyHours,
  settings,
  today,
  todayCapacity,
  capacityRules,
}: {
  courses: Course[];
  completedLectureNumbers: Map<string, Set<number>>;
  completedStudyItems: Map<string, Map<string, Set<number>>>;
  completedGeneratedTitles: Set<string>;
  taskDeadlines: Map<string, string>;
  taskOrders: Map<string, number>;
  generatedTasks: StudyTask[];
  dailyHours: Map<string, number>;
  settings: StudyState["settings"] & { maxDailyHours: number; planEndDate?: string };
  today: string;
  todayCapacity: number;
  capacityRules: CapacityRules;
}) {
  const studyHoursByCourse = new Map(
    courses.map((course) => [
      course.id,
      studyHoursForCourse(
        course,
        completedLectureNumbers.get(course.id) ?? new Set(),
        completedStudyItems.get(course.id) ?? new Map(),
      ),
    ]),
  );
  const effectiveStudyDeadlines = resolveEffectiveStudyDeadlines(
    courses,
    studyHoursByCourse,
    settings,
    today,
    todayCapacity,
    capacityRules,
  );
  const queues = new Map<string, CourseWorkQueue>();
  courses.forEach((course, index) => {
    const studyBlocks = createStudyBlocks(
      course,
      today,
      completedLectureNumbers.get(course.id) ?? new Set(),
      completedStudyItems.get(course.id) ?? new Map(),
      effectiveStudyDeadlines.get(course.id),
      taskDeadlines,
      taskOrders,
    );
    const revisionBlocks = course.requiresRevision
      ? createRevisionBlocks(course, today)
      : [];
    const blocks = [...studyBlocks, ...revisionBlocks]
      .filter((block) => !completedGeneratedTitles.has(blockKey(course.id, block.type, block.title)))
      .sort((a, b) => (a.stage === b.stage ? 0 : a.stage === "study" ? -1 : 1) || a.sequence - b.sequence);
    queues.set(course.id, { course, blocks, originalIndex: index });
  });

  const maxDeadline = latestRealDeadline(courses);
  const horizon = addDays(maxDate(settings.planEndDate ?? today, maxDeadline ?? addDays(today, 365)), 180);
  const scheduledTodayByCourse = new Map<string, Map<string, number>>();
  const dependencyCompletionDates = new Map<string, string>();
  let cursor = today;
  let guard = 0;

  while (hasRemainingWork(queues) && cursor <= horizon && guard < 1200) {
    guard += 1;
    const capacity = capacityForDate(cursor, settings.maxDailyHours, today, todayCapacity, capacityRules);
    const used = dailyHours.get(cursor) ?? 0;
    let remainingCapacity = roundToOne(capacity - used);

    while (hasRemainingWork(queues)) {
      const candidate = chooseNextBlock({
        queues,
        date: cursor,
        remainingCapacity,
        settings,
        today,
        todayCapacity,
        capacityRules,
        scheduledToday: scheduledTodayByCourse.get(cursor) ?? new Map(),
        dependencyCompletionDates,
      });
      if (!candidate) break;

      const { queue, block } = candidate;
      const scheduledTask = makeTaskFromBlock(block, cursor);
      generatedTasks.push(scheduledTask);
      queue.blocks.shift();
      if (block.stage === "study" && !queue.blocks.some((item) => item.stage === "study")) {
        dependencyCompletionDates.set(queue.course.id, cursor);
      }
      dailyHours.set(cursor, roundToOne((dailyHours.get(cursor) ?? 0) + block.hours));
      const courseDayCounts = scheduledTodayByCourse.get(cursor) ?? new Map<string, number>();
      courseDayCounts.set(queue.course.id, (courseDayCounts.get(queue.course.id) ?? 0) + 1);
      scheduledTodayByCourse.set(cursor, courseDayCounts);
      remainingCapacity = roundToOne(remainingCapacity - block.hours);
      if (remainingCapacity <= 0) break;
    }

    cursor = addDays(cursor, 1);
  }

  if (hasRemainingWork(queues)) {
    for (const queue of queues.values()) {
      while (queue.blocks.length) {
        const block = queue.blocks.shift() as WorkBlock;
        generatedTasks.push(makeTaskFromBlock(block, cursor));
        dailyHours.set(cursor, roundToOne((dailyHours.get(cursor) ?? 0) + block.hours));
        cursor = addDays(cursor, 1);
      }
    }
  }
}

function chooseNextBlock({
  queues,
  date,
  remainingCapacity,
  settings,
  today,
  todayCapacity,
  capacityRules,
  scheduledToday,
  dependencyCompletionDates,
}: {
  queues: Map<string, CourseWorkQueue>;
  date: string;
  remainingCapacity: number;
  settings: StudyState["settings"] & { maxDailyHours: number };
  today: string;
  todayCapacity: number;
  capacityRules: CapacityRules;
  scheduledToday: Map<string, number>;
  dependencyCompletionDates: Map<string, string>;
}) {
  const candidates = [...queues.values()]
    .filter((queue) => queue.blocks.length > 0)
    .filter((queue) => dependenciesSatisfied(queue.course, queues, date, dependencyCompletionDates))
    .filter((queue) => {
      const block = queue.blocks[0];
      return block.hours <= remainingCapacity && block.earliestDate <= date;
    })
    .map((queue) => ({
      queue,
      block: queue.blocks[0],
      score: scoreQueue(queue, queues, date, settings, today, todayCapacity, capacityRules, scheduledToday),
    }))
    .sort((a, b) => b.score - a.score || compareQueueTie(a.queue, b.queue));

  return candidates[0];
}

function scoreQueue(
  queue: CourseWorkQueue,
  queues: Map<string, CourseWorkQueue>,
  date: string,
  settings: StudyState["settings"] & { maxDailyHours: number },
  today: string,
  todayCapacity: number,
  capacityRules: CapacityRules,
  scheduledToday: Map<string, number>,
) {
  const course = queue.course;
  const block = queue.blocks[0];
  const deadline = realBlockDeadline(block);
  const priorityScore = { high: 340, medium: 190, low: 80 }[course.priority];
  const orderScore = Math.max(0, 120 - planningOrder(course, new Map([[course.id, queue.originalIndex + 1]])) * 8);
  const repeatedTodayPenalty = (scheduledToday.get(course.id) ?? 0) * 65;
  const stageScore = block.stage === "study" ? 360 : 0;

  if (!deadline) {
    return stageScore + priorityScore + orderScore - repeatedTodayPenalty;
  }

  const remainingHours = queue.blocks
    .filter((item) => {
      const itemDeadline = realBlockDeadline(item);
      return itemDeadline !== undefined && itemDeadline <= deadline;
    })
    .reduce((total, item) => total + item.hours, 0);
  const capacityUntilDeadline = capacityBetween(date, deadline, settings.maxDailyHours, today, todayCapacity, capacityRules);
  const latestSafeStart = latestSafeStartDate(deadline, remainingHours, settings.maxDailyHours, today, todayCapacity, capacityRules);
  const daysUntilSafe = daysBetween(date, latestSafeStart);
  const slack = capacityUntilDeadline - remainingHours;
  const unsafeScore = date >= latestSafeStart ? 5000 + Math.abs(Math.min(daysUntilSafe, 0)) * 500 : 1200 / Math.max(daysUntilSafe + 1, 1);
  const slackScore = Math.max(0, 700 - Math.max(slack, 0) * 35);
  const dueSoonScore = 500 / Math.max(daysBetween(date, deadline), 1);
  const prepScore = block.stage === "revision" ? revisionPriorityScore(block, date, queues, settings, today, todayCapacity, capacityRules) : 0;

  return unsafeScore + slackScore + dueSoonScore + stageScore + prepScore + priorityScore + orderScore - repeatedTodayPenalty;
}

function revisionPriorityScore(
  block: WorkBlock,
  date: string,
  queues: Map<string, CourseWorkQueue>,
  settings: StudyState["settings"] & { maxDailyHours: number },
  today: string,
  todayCapacity: number,
  capacityRules: CapacityRules,
) {
  const examDate = block.course.examDate;
  if (!examDate || date < examPrepStartDate(examDate)) return -10_000;

  const urgentStudyExists = [...queues.values()].some((queue) => {
    const nextBlock = queue.blocks[0];
    if (!nextBlock || nextBlock.stage !== "study") return false;
    const deadline = realBlockDeadline(nextBlock);
    if (!deadline) return false;
    const remainingHours = queue.blocks
      .filter((item) => item.stage === "study" && realBlockDeadline(item) === deadline)
      .reduce((total, item) => total + item.hours, 0);
    const safeStart = latestSafeStartDate(deadline, remainingHours, settings.maxDailyHours, today, todayCapacity, capacityRules);
    return date >= safeStart || capacityBetween(date, deadline, settings.maxDailyHours, today, todayCapacity, capacityRules) <= remainingHours + block.hours;
  });

  const mockPenalty = block.type === "mock" && urgentStudyExists ? -8_000 : 0;
  const examSoonScore = 900 / Math.max(daysBetween(date, examDate), 1);
  return examSoonScore + mockPenalty;
}

function compareQueueTie(a: CourseWorkQueue, b: CourseWorkQueue) {
  const priorityCompare = priorityWeight[a.course.priority] - priorityWeight[b.course.priority];
  if (priorityCompare !== 0) return priorityCompare;
  const deadlineCompare = planningSortDate(a.course).localeCompare(planningSortDate(b.course));
  if (deadlineCompare !== 0) return deadlineCompare;
  const orderCompare = planningOrder(a.course, new Map([[a.course.id, a.originalIndex + 1], [b.course.id, b.originalIndex + 1]])) -
    planningOrder(b.course, new Map([[a.course.id, a.originalIndex + 1], [b.course.id, b.originalIndex + 1]]));
  if (orderCompare !== 0) return orderCompare;
  return a.course.name.localeCompare(b.course.name);
}

function makeTaskFromBlock(block: WorkBlock, date: string): StudyTask {
  return {
    id: `auto-${date}-${block.course.id}-${slug(block.title)}`,
    date,
    deadline: block.deadline,
    customDeadline: block.customDeadline,
    title: block.title,
    subject: block.course.name,
    courseId: block.course.id,
    lectureNumbers: block.type === "lecture" ? lectureNumbersFromTitle(block.title) : undefined,
    studyMethodId: block.method?.id,
    studyMethodItem: block.methodItem,
    type: block.type,
    phase: "Auto plan",
    estimatedHours: block.hours,
    completed: false,
    autoGenerated: true,
    planningOrder: block.sequence,
  };
}

function hasRemainingWork(queues: Map<string, CourseWorkQueue>) {
  return [...queues.values()].some((queue) => queue.blocks.length > 0);
}

function dependenciesSatisfied(
  course: Course,
  queues: Map<string, CourseWorkQueue>,
  date: string,
  dependencyCompletionDates: Map<string, string>,
) {
  return getDependencyIds(course).every((dependencyId) => {
    const dependencyQueue = queues.get(dependencyId);
    if (!dependencyQueue) return true;
    if (dependencyQueue.blocks.some((block) => block.stage === "study")) return false;
    const completedOn = dependencyCompletionDates.get(dependencyId);
    return !completedOn || completedOn < date;
  });
}

function realBlockDeadline(block: WorkBlock) {
  if (block.stage === "revision") return block.hardDeadline ?? block.deadline;
  return block.deadline;
}

function latestRealDeadline(courses: Course[]) {
  return courses
    .flatMap((course) => [course.targetFinishDate, course.examDate])
    .filter((date): date is string => Boolean(date))
    .sort()
    .at(-1);
}

function capacityBetween(
  startDate: string,
  endDate: string,
  maxDailyHours: number,
  today: string,
  todayCapacity: number,
  capacityRules: CapacityRules,
) {
  return dateRange(startDate, endDate).reduce(
    (total, date) => total + capacityForDate(date, maxDailyHours, today, todayCapacity, capacityRules),
    0,
  );
}

function latestSafeStartDate(
  deadline: string,
  remainingHours: number,
  maxDailyHours: number,
  today: string,
  todayCapacity: number,
  capacityRules: CapacityRules,
) {
  let accumulated = 0;
  let cursor = deadline;
  let guard = 0;

  while (cursor >= today && guard < 800) {
    accumulated += capacityForDate(cursor, maxDailyHours, today, todayCapacity, capacityRules);
    if (accumulated >= remainingHours) return cursor;
    cursor = addDays(cursor, -1);
    guard += 1;
  }

  return today;
}

function daysBetween(start: string, end: string) {
  const startTime = new Date(`${start}T00:00:00`).getTime();
  const endTime = new Date(`${end}T00:00:00`).getTime();
  return Math.ceil((endTime - startTime) / (1000 * 60 * 60 * 24));
}

function studyHoursForCourse(course: Course, completedNumbers: Set<number>, completedStudyItems: Map<string, Set<number>>) {
  return getStudyMethods(course).reduce((total, method) => {
    const completedItems = completedStudyItems.get(method.id) ?? new Set<number>();
    let remainingItems = 0;
    for (let item = 1; item <= method.totalItems; item += 1) {
      const completed = method.id === "lectures"
        ? completedNumbers.has(item)
        : completedItems.has(item);
      if (!completed) remainingItems += 1;
    }
    return total + remainingItems * method.hoursPerItem;
  }, 0);
}

function resolveEffectiveStudyDeadlines(
  courses: Course[],
  studyHoursByCourse: Map<string, number>,
  settings: StudyState["settings"] & { maxDailyHours: number },
  today: string,
  todayCapacity: number,
  capacityRules: CapacityRules,
) {
  const deadlines = new Map<string, string>();
  for (const course of courses) {
    const ownDeadline = course.targetFinishDate ?? course.examDate;
    if (ownDeadline) deadlines.set(course.id, ownDeadline);
  }

  for (let pass = 0; pass < courses.length + 2; pass += 1) {
    let changed = false;
    for (const course of courses) {
      const courseDeadline = deadlines.get(course.id);
      if (!courseDeadline) continue;

      const courseStudyHours = Math.max(studyHoursByCourse.get(course.id) ?? 0, 0.1);
      const latestCourseStart = latestSafeStartDate(
        courseDeadline,
        courseStudyHours,
        settings.maxDailyHours,
        today,
        todayCapacity,
        capacityRules,
      );
      const dependencyDeadline = addDays(latestCourseStart, -1);

      for (const dependencyId of getDependencyIds(course)) {
        const current = deadlines.get(dependencyId);
        if (!current || dependencyDeadline < current) {
          deadlines.set(dependencyId, dependencyDeadline);
          changed = true;
        }
      }
    }
    if (!changed) break;
  }

  return deadlines;
}

function createStudyBlocks(
  course: Course,
  earliestDate: string,
  completedNumbers: Set<number>,
  completedStudyItems: Map<string, Set<number>>,
  deadline?: string,
  taskDeadlines = new Map<string, string>(),
  taskOrders = new Map<string, number>(),
): WorkBlock[] {
  const blocks: WorkBlock[] = [];
  const methods = getStudyMethods(course);
  let globalSequence = 0;

  for (const method of methods) {
    const completedItems = completedStudyItems.get(method.id) ?? new Set<number>();
    let item = 1;
    while (item <= method.totalItems) {
      globalSequence += 1;
      const completed = method.id === "lectures"
        ? completedNumbers.has(item)
        : completedItems.has(item);
      if (completed) {
        item += 1;
        continue;
      }

      const title = method.taskType === "lecture" ? `${course.name} L${item}` : `${course.name} ${method.name} ${item}`;
      const overrideDeadline = taskDeadlines.get(taskDeadlineKey(course.id, method.id, item)) ?? taskDeadlines.get(blockKey(course.id, method.taskType, title));
      const overrideOrder = taskOrders.get(taskDeadlineKey(course.id, method.id, item)) ?? taskOrders.get(blockKey(course.id, method.taskType, title));

      blocks.push({
        course,
        method,
        title,
        type: method.taskType,
        stage: "study",
        hours: roundToOne(method.hoursPerItem),
        deadline: overrideDeadline ?? deadline,
        customDeadline: overrideDeadline,
        hardDeadline: overrideDeadline ?? deadline,
        earliestDate,
        sequence: overrideOrder ?? 10_000 + globalSequence,
        methodItem: item,
      });
      item += 1;
    }
  }

  return blocks;
}

function createRevisionBlocks(course: Course, earliestDate: string): WorkBlock[] {
  const courseDeadline = course.targetFinishDate ?? course.examDate ?? addDays(earliestDate, 365);
  const revisionDeadline = course.examDate ? addDays(course.examDate, -1) : courseDeadline;
  const revisionStart = course.examDate
    ? maxDate(earliestDate, examPrepStartDate(course.examDate))
    : maxDate(earliestDate, addDays(courseDeadline, 1));
  const planningDeadline = preferredRevisionDeadline(course, revisionStart, revisionDeadline);
  return [
    {
      course,
      title: `${course.name} revision block 1`,
      type: "revision",
      stage: "revision",
      hours: 2,
      deadline: planningDeadline,
      hardDeadline: revisionDeadline,
      earliestDate: revisionStart,
      sequence: course.totalLectures + 1,
    },
    {
      course,
      title: `${course.name} revision block 2`,
      type: "revision",
      stage: "revision",
      hours: 2,
      deadline: planningDeadline,
      hardDeadline: revisionDeadline,
      earliestDate: revisionStart,
      sequence: course.totalLectures + 2,
    },
    {
      course,
      title: `${course.name} mock exam`,
      type: "mock",
      stage: "revision",
      hours: 3,
      deadline: planningDeadline,
      hardDeadline: revisionDeadline,
      earliestDate: revisionStart,
      sequence: course.totalLectures + 3,
    },
  ];
}

function examPrepStartDate(examDate: string) {
  return addDays(examDate, -EXAM_PREP_WINDOW_DAYS);
}

function findMinimumDailyLimit(
  state: StudyState,
  options: { today: string; endDate?: string; holidays?: string[]; customStudyHours?: Array<{ date: string; hours: number }>; restrictedDays?: Array<{ date: string; maxHours: number }>; minDailyHours: number; maxDailyHours: number },
) {
  for (let cap = options.minDailyHours; cap <= options.maxDailyHours; cap += 0.5) {
    const plan = autoPlanSchedule(state, {
      today: options.today,
      maxDailyHours: cap,
      endDate: options.endDate,
      holidays: options.holidays,
      customStudyHours: options.customStudyHours,
      restrictedDays: options.restrictedDays,
      ignoreTodayClock: true,
    });
    if (!planDeadlineMiss(plan) && !planRangeMiss(plan) && !planCapacityMiss(plan, options.today)) return cap;
  }

  return undefined;
}

function planDeadlineMiss(state: StudyState) {
  const misses = state.courses
    .map((course) => {
      const finishDate = projectedCourseFinishDate(state.tasks, course.id);
      if (!course.targetFinishDate || !finishDate || finishDate <= course.targetFinishDate) return undefined;
      return {
        courseName: course.name,
        deadline: course.targetFinishDate,
        latestScheduledDate: finishDate,
      };
    })
    .filter((item): item is { courseName: string; deadline: string; latestScheduledDate: string } => Boolean(item))
    .sort((a, b) => a.latestScheduledDate.localeCompare(b.latestScheduledDate));

  return misses.at(-1);
}

function planRangeMiss(state: StudyState) {
  const rangeEnd = state.settings?.planEndDate;
  if (!rangeEnd) return undefined;
  const latestScheduledDate = state.tasks
    .filter((task) => task.autoGenerated)
    .map((task) => task.date)
    .sort()
    .at(-1);
  if (!latestScheduledDate || latestScheduledDate <= rangeEnd) return undefined;
  return { rangeEnd, latestScheduledDate };
}

function planCapacityMiss(state: StudyState, today: string) {
  const settings = state.settings;
  if (!settings) return undefined;
  const maxDailyHours = settings.maxDailyHours;
  const rules: CapacityRules = {
    today,
    todayCapacity: maxDailyHours,
    holidays: new Set(settings.holidays ?? []),
    customStudyHours: new Map((settings.customStudyHours ?? migrateRestrictedDays(settings.restrictedDays)).map((day) => [day.date, day.hours])),
  };
  const dailyHours = new Map<string, number>();

  for (const task of state.tasks) {
    if (task.type === "exam" || task.type === "rest") continue;
    dailyHours.set(task.date, roundToOne((dailyHours.get(task.date) ?? 0) + task.estimatedHours));
  }

  for (const [date, hours] of [...dailyHours.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
    const capacity = capacityForDate(date, maxDailyHours, today, maxDailyHours, rules);
    if (hours > capacity) return { date, hours, capacity };
  }

  return undefined;
}

function planningOrder(course: Course, originalOrder: Map<string, number>) {
  return course.planningOrder ?? originalOrder.get(course.id) ?? 9999;
}

function planningSortDate(course: Course) {
  return course.targetFinishDate ?? course.examDate ?? "9999-12-31";
}

function preferredRevisionDeadline(course: Course, earliestDate: string, hardDeadline: string) {
  return hardDeadline < earliestDate ? earliestDate : hardDeadline;
}

function dateRange(start: string, end: string) {
  if (start > end) return [];

  const dates: string[] = [];
  const cursor = new Date(`${start}T00:00:00`);
  const last = new Date(`${end}T00:00:00`);

  while (cursor <= last) {
    dates.push(dateKey(cursor));
    cursor.setDate(cursor.getDate() + 1);
  }

  return dates;
}

function maxDate(a: string, b: string) {
  return a > b ? a : b;
}

function capacityForDate(date: string, maxDailyHours: number, today: string, todayCapacity: number, rules: CapacityRules) {
  if (rules.holidays.has(date)) return 0;
  const base = date === today ? todayCapacity : maxDailyHours;
  const customHours = rules.customStudyHours.get(date);
  return customHours === undefined ? base : customHours;
}

function migrateRestrictedDays(days?: Array<{ date: string; maxHours: number }>) {
  return (days ?? []).map((day) => ({ date: day.date, hours: day.maxHours }));
}

function isGeneratedRestTask(task: StudyTask) {
  return task.type === "rest" && task.estimatedHours === 0 && (task.autoGenerated || /^rest$/i.test(task.title.trim()));
}

function slug(value: string) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function blockKey(courseId: string | undefined, type: TaskType, title: string) {
  return `${courseId ?? "general"}:${type}:${title}`;
}

function taskDeadlineKey(courseId: string, methodId: string, item: number) {
  return `${courseId}:${methodId}:${item}`;
}

function getTaskDeadlineOverrides(tasks: StudyTask[]) {
  const deadlines = new Map<string, string>();
  for (const task of tasks) {
    if (!task.courseId || !task.customDeadline) continue;
    if (task.studyMethodId && task.studyMethodItem) {
      deadlines.set(taskDeadlineKey(task.courseId, task.studyMethodId, task.studyMethodItem), task.customDeadline);
    }
    deadlines.set(blockKey(task.courseId, task.type, task.title), task.customDeadline);
  }
  return deadlines;
}

function getTaskOrderOverrides(tasks: StudyTask[]) {
  const orders = new Map<string, number>();
  for (const task of tasks) {
    if (!task.courseId || typeof task.planningOrder !== "number" || !Number.isFinite(task.planningOrder)) continue;
    if (task.studyMethodId && task.studyMethodItem) {
      orders.set(taskDeadlineKey(task.courseId, task.studyMethodId, task.studyMethodItem), task.planningOrder);
    }
    orders.set(blockKey(task.courseId, task.type, task.title), task.planningOrder);
  }
  return orders;
}

function getDependencyIds(course: Course) {
  return course.dependsOnIds?.length ? course.dependsOnIds : course.dependsOnId ? [course.dependsOnId] : [];
}

function getStudyMethods(course: Course): StudyMethod[] {
  return course.studyMethods !== undefined
    ? course.studyMethods
    : [
        {
          id: "lectures",
          name: "Lecture",
          totalItems: course.totalLectures,
          completedItems: course.completedLectures,
          hoursPerItem: course.hoursPerLecture,
          taskType: "lecture",
        },
      ];
}

function getCompletedLectureNumbers(state: StudyState) {
  const result = new Map<string, Set<number>>();

  for (const course of state.courses) {
    const completed = new Set<number>();
    const baseline = Math.min(course.baselineCompletedLectures ?? course.completedLectures, course.totalLectures);
    for (let lecture = 1; lecture <= baseline; lecture += 1) {
      completed.add(lecture);
    }
    result.set(course.id, completed);
  }

  for (const task of state.tasks) {
    if (!task.completed || !task.courseId) continue;
    const completed = result.get(task.courseId);
    if (!completed) continue;
    if (task.type !== "lecture") continue;
    const lectureNumbers = task.lectureNumbers?.length ? task.lectureNumbers : lectureNumbersFromTitle(task.title);
    for (const lecture of lectureNumbers) {
      completed.add(lecture);
    }
  }

  return result;
}

function getCompletedStudyItems(state: StudyState) {
  const result = new Map<string, Map<string, Set<number>>>();

  for (const course of state.courses) {
    const byMethod = new Map<string, Set<number>>();
    for (const method of getStudyMethods(course)) {
      const completed = new Set<number>();
      for (let item = 1; item <= Math.min(method.completedItems, method.totalItems); item += 1) {
        completed.add(item);
      }
      byMethod.set(method.id, completed);
    }
    result.set(course.id, byMethod);
  }

  for (const task of state.tasks) {
    if (!task.completed || !task.courseId || !task.studyMethodId || !task.studyMethodItem) continue;
    const byMethod = result.get(task.courseId);
    const completed = byMethod?.get(task.studyMethodId);
    completed?.add(task.studyMethodItem);
    const titleItem = task.title.match(/(\d+)\s*$/)?.[1];
    if (titleItem) completed?.add(Number(titleItem));
  }

  return result;
}
