import type { Course, CourseProgress, Priority, RiskLevel, StudyTask, StudyState } from "./types";

export function dateKey(date: Date) {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

export const PLAN_START_DATE = dateKey(new Date());

export function todayKey(date = new Date()) {
  return dateKey(date);
}

export function formatDate(dateKeyValue: string) {
  const [year, month, day] = dateKeyValue.split("-");
  return year && month && day ? `${day}.${month}.${year.slice(-2)}` : dateKeyValue;
}

export function getRiskLevel(hours: number): RiskLevel {
  if (hours <= 5) return "Low";
  if (hours <= 8) return "Medium";
  if (hours <= 10) return "High";
  return "Critical";
}

export function sumHours(tasks: StudyTask[]) {
  return tasks.reduce((total, task) => total + task.estimatedHours, 0);
}

export function calculateCourseProgress(state: StudyState, today = todayKey()): CourseProgress[] {
  return state.courses.map((course) => {
    const methods = course.studyMethods !== undefined ? course.studyMethods : [{
      id: "lectures",
      name: "Lecture",
      totalItems: course.totalLectures,
      completedItems: course.completedLectures,
      hoursPerItem: course.hoursPerLecture,
      taskType: "lecture" as const,
    }];
    const totalItems = methods.reduce((total, method) => total + method.totalItems, 0);
    const completedItems = clamp(
      methods.reduce((total, method) => total + method.completedItems, 0),
      0,
      totalItems,
    );
    const remainingItems = Math.max(totalItems - completedItems, 0);
    const remainingHours = methods.reduce(
      (total, method) => total + Math.max(method.totalItems - method.completedItems, 0) * method.hoursPerItem,
      0,
    );
    const progressPercent =
      totalItems === 0 ? 100 : Math.round((completedItems / totalItems) * 100);
    const fallbackDate = course.targetFinishDate ?? course.examDate ?? addDays(today, 365);
    const daysLeft = Math.max(daysBetween(today, fallbackDate), 1);
    const planningTargetDate = priorityPlanningTargetDate(course, today);
    const planningDaysLeft = Math.max(daysBetween(today, planningTargetDate), 1);
    const expectedFinishDate = projectedCourseFinishDate(state.tasks, course.id);

    return {
      ...course,
      completedLectures: completedItems,
      remainingLectures: remainingItems,
      remainingHours,
      progressPercent,
      dailyHoursNeeded: roundToOne(remainingHours / daysLeft),
      priorityBufferDays: priorityBufferDays(course.priority),
      planningTargetDate,
      planningDailyHoursNeeded: roundToOne(remainingHours / planningDaysLeft),
      expectedFinishDate,
      deadlineMissed: Boolean(course.targetFinishDate && expectedFinishDate && expectedFinishDate > course.targetFinishDate),
    };
  });
}

export function projectedCourseFinishDate(tasks: StudyTask[], courseId: string) {
  return tasks
    .filter((task) => task.courseId === courseId)
    .filter((task) => task.autoGenerated || task.completed)
    .filter((task) => !["exam", "rest", "revision", "mock"].includes(task.type))
    .map((task) => task.date)
    .sort()
    .at(-1);
}

export function priorityBufferDays(priority: Priority) {
  if (priority === "high") return 4;
  if (priority === "medium") return 2;
  return 0;
}

export function priorityPlanningDeadline(course: Course) {
  return addDays(course.targetFinishDate ?? course.examDate ?? addDays(todayKey(), 365), -priorityBufferDays(course.priority));
}

export function priorityPlanningTargetDate(course: Course, today = todayKey()) {
  if (!course.targetFinishDate) return course.examDate ?? addDays(today, 365);
  const bufferedDate = priorityPlanningDeadline(course);
  if (bufferedDate <= today) return course.targetFinishDate;
  return minDate(bufferedDate, course.targetFinishDate);
}

export function priorityMeaning(priority: Priority) {
  if (priority === "high") return "Scheduled first with a 4-day buffer";
  if (priority === "medium") return "Balanced scheduling with a 2-day buffer";
  return "Flexible scheduling with no extra buffer";
}

export function groupTasksByDate(tasks: StudyTask[]) {
  return [...tasks]
    .sort((a, b) => a.date.localeCompare(b.date))
    .reduce<Record<string, StudyTask[]>>((groups, task) => {
      groups[task.date] = groups[task.date] ?? [];
      groups[task.date].push(task);
      return groups;
    }, {});
}

export function splitTasks(tasks: StudyTask[], today = todayKey()) {
  return {
    completed: tasks.filter((task) => task.completed),
    remaining: tasks.filter((task) => !task.completed && task.date >= today),
    overdue: tasks.filter((task) => !task.completed && task.date < today),
  };
}

export function roundToOne(value: number) {
  return Math.round(value * 10) / 10;
}

export function lectureCountFromTitle(title: string) {
  return lectureNumbersFromTitle(title).length;
}

export function lectureNumbersForTask(task: StudyTask) {
  return task.lectureNumbers?.length ? task.lectureNumbers : lectureNumbersFromTitle(task.title);
}

export function lectureNumbersFromTitle(title: string) {
  const rangeMatch = title.match(/\bL(\d+)\s*[-\u2013]\s*L?(\d+)\b/i);
  if (rangeMatch) {
    const start = Number(rangeMatch[1]);
    const end = Number(rangeMatch[2]);
    const low = Math.min(start, end);
    const high = Math.max(start, end);
    return Array.from({ length: high - low + 1 }, (_, index) => low + index);
  }

  const singleMatch = title.match(/\bL(\d+)\b/i);
  return singleMatch ? [Number(singleMatch[1])] : [];
}

function daysBetween(start: string, end: string) {
  const startTime = new Date(`${start}T00:00:00`).getTime();
  const endTime = new Date(`${end}T00:00:00`).getTime();
  const day = 1000 * 60 * 60 * 24;
  return Math.ceil((endTime - startTime) / day) + 1;
}

function minDate(a: string, b: string) {
  return a < b ? a : b;
}

export function addDays(date: string, days: number) {
  const next = new Date(`${date}T00:00:00`);
  next.setDate(next.getDate() + days);
  return dateKey(next);
}

function clamp(value: number, min: number, max: number) {
  return Math.min(Math.max(value, min), max);
}
