export type TaskType =
  | "lecture"
  | "coding"
  | "revision"
  | "mock"
  | "recap"
  | "summary"
  | "exam"
  | "rest";

export type Priority = "high" | "medium" | "low";

export type StudyMethod = {
  id: string;
  name: string;
  totalItems: number;
  completedItems: number;
  hoursPerItem: number;
  taskType: TaskType;
};

export type Course = {
  id: string;
  name: string;
  examDate?: string;
  totalLectures: number;
  baselineCompletedLectures?: number;
  completedLectures: number;
  hoursPerLecture: number;
  targetFinishDate?: string;
  priority: Priority;
  planningOrder?: number;
  hasExam: boolean;
  requiresRevision: boolean;
  dependsOnId?: string;
  dependsOnIds?: string[];
  studyMethods?: StudyMethod[];
};

export type StudyTask = {
  id: string;
  date: string;
  deadline?: string;
  customDeadline?: string;
  title: string;
  subject: string;
  courseId?: string;
  lectureNumbers?: number[];
  type: TaskType;
  phase: string;
  estimatedHours: number;
  completed: boolean;
  autoGenerated?: boolean;
  origin?: "generated" | "manual";
  locked?: boolean;
  dirty?: boolean;
  completedAt?: string;
  studyDayDate?: string;
  studyMethodId?: string;
  studyMethodItem?: number;
  planningOrder?: number;
};

export type BoardColumn = "todo" | "inProgress" | "done";

export type BoardNote = {
  id: string;
  title: string;
  body: string;
  column: BoardColumn;
  linkedCourseId?: string;
  linkedTaskId?: string;
  createdAt: string;
};

export type StudyState = {
  courses: Course[];
  tasks: StudyTask[];
  boardNotes?: BoardNote[];
  settings?: PlannerSettings;
  profile?: UserProfile;
};

export type PlannerCapacityWarning = {
  currentDailyLimit: number;
  suggestedDailyLimit?: number;
  latestScheduledDate: string;
  message: string;
  severity?: "today" | "deadline";
  issues?: PlannerValidationIssue[];
};

export type PlannerValidationIssue = {
  type: "capacity" | "deadline" | "dependency" | "holiday" | "order" | "revision";
  severity: "warning" | "error";
  message: string;
  date?: string;
  courseId?: string;
  taskId?: string;
};

export type CourseProgress = Course & {
  completedLectures: number;
  remainingLectures: number;
  remainingHours: number;
  progressPercent: number;
  dailyHoursNeeded: number;
  priorityBufferDays: number;
  planningTargetDate: string;
  planningDailyHoursNeeded: number;
  expectedFinishDate?: string;
  deadlineMissed: boolean;
};

export type RiskLevel = "Low" | "Medium" | "High" | "Critical";

export type PlannerSettings = {
  autoPlan: boolean;
  autoPlanIntervalHours: number;
  maxDailyHours: number;
  startDate: string;
  planEndDate?: string;
  holidays?: string[];
  customStudyHours?: Array<{ date: string; hours: number }>;
  restrictedDays?: Array<{ date: string; maxHours: number }>;
  defaultTaskHours: number;
  warningThresholdHours: number;
  showCompletedTasks: boolean;
  weekStartsOn: "monday" | "sunday";
  reminderTime: string;
  lateNightPromptEnabled: boolean;
  lateNightPromptAfterHour: number;
  lateNightMaxExtensionHour: number;
  studyDayOverride?: { studyDate: string; expiresAt: string };
  language: "en" | "de" | "pl" | "it";
  theme: "razor" | "biaBee" | "tofu";
  lastAutoPlanDate?: string;
  lastAutoPlanAt?: string;
};

export type UserProfile = {
  name: string;
  birthday: string;
  institution: string;
};
